name: Lint

on: [pull_request, workflow_dispatch]

jobs:
  trunk_check_runner:
    name: Trunk Check runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: bahmutov/npm-install@v1
      #   with:
      #     install-command: npm ci --legacy-peer-deps
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.1
